### PR TITLE
Fix modman mapping.

### PR DESCRIPTION
**Pull request by nocturnalfrog**
The modman file was very out of date.

### CODE REVIEW

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #20053 ( https://affirm.desk.com/web/agent/case/20053 )

Affirm | Aug 30, 2017 06:36PM UTC

------------------------------------------------------------------------------------------------------------
Case #20053
Customer: Affirm/Magento_Affirm
Subject: [Affirm/Magento_Affirm] Fix modman mapping. (#32)
------------------------------------------------------------------------------------------------------------
Case Information (20053):

Subject: [Affirm/Magento_Affirm] Fix modman mapping. (#32)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at AUG 30, 2017 | 11:36AM PDT:
The modman file was very out of date.
You can view, comment on, or merge this pull request online at:

  https://github.com/Affirm/Magento_Affirm/pull/32

-- Commit Summary --

  * Fix modman mapping.

-- File Changes --

    M modman (14)

-- Patch Links --

https://github.com/Affirm/Magento_Affirm/pull/32.patch
https://github.com/Affirm/Magento_Affirm/pull/32.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/32


------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #20053
------------------------------------------------------------------------------------------------------------

**Comment by nocturnalfrog** [comment]
Is this still being reviewed?

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #21400 ( https://affirm.desk.com/web/agent/case/21400 )

Affirm | Sep 13, 2017 07:32PM UTC

------------------------------------------------------------------------------------------------------------
Case #21400
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)
------------------------------------------------------------------------------------------------------------
Case Information (21400):

Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at SEP 13, 2017 | 12:32PM PDT:
Is this still being reviewed?

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/32#issuecomment-329272697

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #21400
------------------------------------------------------------------------------------------------------------

**Comment by nandadubey** [comment]
We are looking into it, will update it with our next version release.

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #21496 ( https://affirm.desk.com/web/agent/case/21496 )

Affirm | Sep 14, 2017 07:56PM UTC

------------------------------------------------------------------------------------------------------------
Case #21496
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)
------------------------------------------------------------------------------------------------------------
Case Information (21496):

Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at SEP 14, 2017 | 12:56PM PDT:
We are looking into it, will update it with our next version release.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/32#issuecomment-329591471

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #21496
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #21498 ( https://affirm.desk.com/web/agent/case/21498 )

Affirm | Sep 14, 2017 08:06PM UTC

------------------------------------------------------------------------------------------------------------
Case #21498
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)
------------------------------------------------------------------------------------------------------------
Case Information (21498):

Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at SEP 14, 2017 | 01:06PM PDT:
nandadubey approved this pull request.

lgtm



-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/32#pullrequestreview-62870775

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #21498
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #21513 ( https://affirm.desk.com/web/agent/case/21513 )

Affirm | Sep 14, 2017 08:39PM UTC

------------------------------------------------------------------------------------------------------------
Case #21513
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)
------------------------------------------------------------------------------------------------------------
Case Information (21513):

Subject: Re: [Affirm/Magento_Affirm] Fix modman mapping. (#32)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at SEP 14, 2017 | 01:39PM PDT:
Closed #32.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/32#event-1249983282

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #21513
------------------------------------------------------------------------------------------------------------

**Pull request closed without merging**
