### PR TITLE
update messaging for monthly payments

### PR DESCRIPTION
**Pull request by mannygit**

### CODE REVIEW

**Comment by mannygit** [comment]
@AaronL21 please take a look

**Comment by AaronL21** [comment]
Thanks. Can you use the latest messaging "Buy with Monthly Payments" that
Chris added. Besides that, it looks good to go.

On Thu, Mar 26, 2015 at 9:25 AM, Manuel Arias <notifications@github.com>
wrote:

> @AaronL21 <https://github.com/AaronL21> please take a look
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Affirm/Magento_Affirm/pull/15#issuecomment-86603084>.
>



-- 
Aaron Ligon
Affirm - Product

email: aaron@affirm.com
cell: 650-814-5640

**Comment by AaronL21** [comment]
Thanks. When you're ready you can release it as 2.0.15.

On Thu, Mar 26, 2015 at 10:51 AM, Manuel Arias <notifications@github.com>
wrote:

> Merged #15 <https://github.com/Affirm/Magento_Affirm/pull/15>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Affirm/Magento_Affirm/pull/15#event-266159886>.
>



-- 
Aaron Ligon
Affirm - Product

email: aaron@affirm.com
cell: 650-814-5640

**Comment by mannygit** [comment]
Done

**Pull request merged**
