### PR TITLE
Issue#27 Fix for magento versions which does not pick current store i…

### PR DESCRIPTION
**Pull request by nandadubey**
…d as default. Admin configuration values explicitly uses storeid scope now.

### CODE REVIEW

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #17719 ( https://affirm.desk.com/web/agent/case/17719 )

Affirm | Jul 25, 2017 09:06PM UTC

------------------------------------------------------------------------------------------------------------
Case #17719
Customer: Affirm/Magento_Affirm
Subject: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)
------------------------------------------------------------------------------------------------------------
Case Information (17719):

Subject: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUL 25, 2017 | 02:05PM PDT:
…d as default. Admin configuration values explicitly uses storeid scope now.
You can view, comment on, or merge this pull request online at:

  https://github.com/Affirm/Magento_Affirm/pull/31

-- Commit Summary --

  * Issue#27 Fix for magento versions which does not pick current store id as default. Admin configuration values explicitly uses storeid scope now.

-- File Changes --

    M extension/app/code/community/Affirm/Affirm/Helper/Data.php (34)

-- Patch Links --

https://github.com/Affirm/Magento_Affirm/pull/31.patch
https://github.com/Affirm/Magento_Affirm/pull/31.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/31


------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #17719
------------------------------------------------------------------------------------------------------------

**Comment by diptib10** [comment]
@nandadubey lgtm

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #17738 ( https://affirm.desk.com/web/agent/case/17738 )

Affirm | Jul 26, 2017 04:56PM UTC

------------------------------------------------------------------------------------------------------------
Case #17738
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)
------------------------------------------------------------------------------------------------------------
Case Information (17738):

Subject: Re: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at JUL 26, 2017 | 09:56AM PDT:
@nandadubey lgtm

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #17738
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #21514 ( https://affirm.desk.com/web/agent/case/21514 )

Affirm | Sep 14, 2017 08:40PM UTC

------------------------------------------------------------------------------------------------------------
Case #21514
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)
------------------------------------------------------------------------------------------------------------
Case Information (21514):

Subject: Re: [Affirm/Magento_Affirm] Issue#27 Fix for magento versions which does not pick current store i… (#31)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at SEP 14, 2017 | 01:40PM PDT:
Closed #31.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/31#event-1249984774

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #21514
------------------------------------------------------------------------------------------------------------

**Pull request closed without merging**
