### PR TITLE
Magento Composer Installer

### PR DESCRIPTION
**Pull request by JoshuaEstes**
We use the Magento Composer Installer to manage all of our extensions. This PR will allow others to install the extension this way. I have also updated the README.md file to show how to do this.

Let me know if there is anything else.

### CODE REVIEW

**Comment by JoshuaEstes** [comment]
@diptib10 Can this get merged in?

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #11577 ( https://affirm.desk.com/web/agent/case/11577 )

Affirm | Feb 03, 2017 05:45PM UTC

------------------------------------------------------------------------------------------------------------
Case #11577
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)
------------------------------------------------------------------------------------------------------------
Case Information (11577):

Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at FEB 03, 2017 | 09:45AM PST:
@diptib10 Can this get merged in?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/21#issuecomment-277313480


------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #11577
------------------------------------------------------------------------------------------------------------

**Comment by diptib10** [comment]
This is part of the new release

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #13960 ( https://affirm.desk.com/web/agent/case/13960 )

Affirm | Apr 25, 2017 09:04PM UTC

------------------------------------------------------------------------------------------------------------
Case #13960
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)
------------------------------------------------------------------------------------------------------------
Case Information (13960):

Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at APR 25, 2017 | 02:04PM PDT:
This is part of the new release

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/21#issuecomment-297164407

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #13960
------------------------------------------------------------------------------------------------------------

**Comment by affirmPE** [comment]
------------------------------------------------------------------------------------------------------------
Type your response on top of this email to respond to this case. Learn Email Commands Here - https://support.desk.com/customer/portal/articles/1191712-reply-via-email-commands
------------------------------------------------------------------------------------------------------------


Case Assignment Notification - Case #13963 ( https://affirm.desk.com/web/agent/case/13963 )

Affirm | Apr 25, 2017 09:19PM UTC

------------------------------------------------------------------------------------------------------------
Case #13963
Customer: Affirm/Magento_Affirm
Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)
------------------------------------------------------------------------------------------------------------
Case Information (13963):

Subject: Re: [Affirm/Magento_Affirm] Magento Composer Installer (#21)

Description: 
Status: Open
Priority: 4

Assigned Group: MTS



------------------------------------------------------------------------------------------------------------
Case History
------------------------------------------------------------------------------------------------------------
 goatmad  at APR 25, 2017 | 02:19PM PDT:
Closed #21.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/Affirm/Magento_Affirm/pull/21#event-1057442267

------------------------------------------------------------------------------------------------------------
This message was sent to reply@reply.github.com in reference to Case #13963
------------------------------------------------------------------------------------------------------------

**Pull request closed without merging**
